[workspace]
authors = ["Jan Kotanski <jankotan@gmail.com>"]
channels = ["conda-forge"]
name = "h5cpp"
platforms = ["linux-64", "linux-aarch64", "osx-arm64", "osx-64", "win-64"]
version = "0.7.1"

[tasks]

[dependencies]
rattler-build = ">=0.60.0,<0.61"
ipython = ">=9.11.0,<10"
python = "==3.14"
conda-smithy = ">=3.56.3,<4"
