var annotated_dup =
[
    [ "hdf5", "namespacehdf5.html", [
      [ "attribute", "namespacehdf5_1_1attribute.html", [
        [ "Attribute", "classhdf5_1_1attribute_1_1Attribute.html", "classhdf5_1_1attribute_1_1Attribute" ],
        [ "AttributeIterator", "classhdf5_1_1attribute_1_1AttributeIterator.html", "classhdf5_1_1attribute_1_1AttributeIterator" ],
        [ "AttributeManager", "classhdf5_1_1attribute_1_1AttributeManager.html", "classhdf5_1_1attribute_1_1AttributeManager" ]
      ] ],
      [ "dataspace", "namespacehdf5_1_1dataspace.html", [
        [ "TypeTrait< std::array< T, N > >", "classhdf5_1_1dataspace_1_1TypeTrait_3_01std_1_1array_3_01T_00_01N_01_4_01_4.html", "classhdf5_1_1dataspace_1_1TypeTrait_3_01std_1_1array_3_01T_00_01N_01_4_01_4" ],
        [ "TypeTrait< std::vector< T > >", "classhdf5_1_1dataspace_1_1TypeTrait_3_01std_1_1vector_3_01T_01_4_01_4.html", "classhdf5_1_1dataspace_1_1TypeTrait_3_01std_1_1vector_3_01T_01_4_01_4" ],
        [ "Dataspace", "classhdf5_1_1dataspace_1_1Dataspace.html", "classhdf5_1_1dataspace_1_1Dataspace" ],
        [ "Hyperslab", "classhdf5_1_1dataspace_1_1Hyperslab.html", "classhdf5_1_1dataspace_1_1Hyperslab" ],
        [ "Points", "classhdf5_1_1dataspace_1_1Points.html", "classhdf5_1_1dataspace_1_1Points" ],
        [ "DataspacePool", "classhdf5_1_1dataspace_1_1DataspacePool.html", "classhdf5_1_1dataspace_1_1DataspacePool" ],
        [ "Scalar", "classhdf5_1_1dataspace_1_1Scalar.html", "classhdf5_1_1dataspace_1_1Scalar" ],
        [ "Selection", "classhdf5_1_1dataspace_1_1Selection.html", "classhdf5_1_1dataspace_1_1Selection" ],
        [ "OperationWithSelection", "structhdf5_1_1dataspace_1_1OperationWithSelection.html", "structhdf5_1_1dataspace_1_1OperationWithSelection" ],
        [ "SelectionManager", "classhdf5_1_1dataspace_1_1SelectionManager.html", "classhdf5_1_1dataspace_1_1SelectionManager" ],
        [ "Simple", "classhdf5_1_1dataspace_1_1Simple.html", "classhdf5_1_1dataspace_1_1Simple" ],
        [ "TypeTrait", "classhdf5_1_1dataspace_1_1TypeTrait.html", "classhdf5_1_1dataspace_1_1TypeTrait" ],
        [ "DataspaceHolder", "classhdf5_1_1dataspace_1_1DataspaceHolder.html", "classhdf5_1_1dataspace_1_1DataspaceHolder" ],
        [ "View", "classhdf5_1_1dataspace_1_1View.html", "classhdf5_1_1dataspace_1_1View" ],
        [ "TypeTrait< ArrayAdapter< T > >", "classhdf5_1_1dataspace_1_1TypeTrait_3_01ArrayAdapter_3_01T_01_4_01_4.html", "classhdf5_1_1dataspace_1_1TypeTrait_3_01ArrayAdapter_3_01T_01_4_01_4" ]
      ] ],
      [ "datatype", "namespacehdf5_1_1datatype.html", [
        [ "Array", "classhdf5_1_1datatype_1_1Array.html", "classhdf5_1_1datatype_1_1Array" ],
        [ "VLengthArray", "classhdf5_1_1datatype_1_1VLengthArray.html", "classhdf5_1_1datatype_1_1VLengthArray" ],
        [ "Compound", "classhdf5_1_1datatype_1_1Compound.html", "classhdf5_1_1datatype_1_1Compound" ],
        [ "Datatype", "classhdf5_1_1datatype_1_1Datatype.html", "classhdf5_1_1datatype_1_1Datatype" ],
        [ "Enum", "classhdf5_1_1datatype_1_1Enum.html", "classhdf5_1_1datatype_1_1Enum" ],
        [ "DatatypeHolder", "classhdf5_1_1datatype_1_1DatatypeHolder.html", "classhdf5_1_1datatype_1_1DatatypeHolder" ],
        [ "Float", "classhdf5_1_1datatype_1_1Float.html", "classhdf5_1_1datatype_1_1Float" ],
        [ "float16_t", "classhdf5_1_1datatype_1_1float16__t.html", "classhdf5_1_1datatype_1_1float16__t" ],
        [ "Integer", "classhdf5_1_1datatype_1_1Integer.html", "classhdf5_1_1datatype_1_1Integer" ],
        [ "String", "classhdf5_1_1datatype_1_1String.html", "classhdf5_1_1datatype_1_1String" ],
        [ "TypeTrait", "classhdf5_1_1datatype_1_1TypeTrait.html", "classhdf5_1_1datatype_1_1TypeTrait" ]
      ] ],
      [ "error", "namespacehdf5_1_1error.html", [
        [ "Descriptor", "structhdf5_1_1error_1_1Descriptor.html", "structhdf5_1_1error_1_1Descriptor" ],
        [ "Singleton", "classhdf5_1_1error_1_1Singleton.html", "classhdf5_1_1error_1_1Singleton" ],
        [ "H5CError", "classhdf5_1_1error_1_1H5CError.html", "classhdf5_1_1error_1_1H5CError" ]
      ] ],
      [ "file", "namespacehdf5_1_1file.html", [
        [ "DirectDriver", "classhdf5_1_1file_1_1DirectDriver.html", "classhdf5_1_1file_1_1DirectDriver" ],
        [ "Driver", "classhdf5_1_1file_1_1Driver.html", "classhdf5_1_1file_1_1Driver" ],
        [ "File", "classhdf5_1_1file_1_1File.html", "classhdf5_1_1file_1_1File" ],
        [ "MemoryDriver", "classhdf5_1_1file_1_1MemoryDriver.html", "classhdf5_1_1file_1_1MemoryDriver" ],
        [ "MPIDriver", "classhdf5_1_1file_1_1MPIDriver.html", "classhdf5_1_1file_1_1MPIDriver" ],
        [ "PosixDriver", "classhdf5_1_1file_1_1PosixDriver.html", "classhdf5_1_1file_1_1PosixDriver" ]
      ] ],
      [ "filter", "namespacehdf5_1_1filter.html", [
        [ "Deflate", "classhdf5_1_1filter_1_1Deflate.html", "classhdf5_1_1filter_1_1Deflate" ],
        [ "ExternalFilter", "classhdf5_1_1filter_1_1ExternalFilter.html", "classhdf5_1_1filter_1_1ExternalFilter" ],
        [ "ExternalFilters", "classhdf5_1_1filter_1_1ExternalFilters.html", "classhdf5_1_1filter_1_1ExternalFilters" ],
        [ "Filter", "classhdf5_1_1filter_1_1Filter.html", "classhdf5_1_1filter_1_1Filter" ],
        [ "Fletcher32", "classhdf5_1_1filter_1_1Fletcher32.html", "classhdf5_1_1filter_1_1Fletcher32" ],
        [ "NBit", "classhdf5_1_1filter_1_1NBit.html", "classhdf5_1_1filter_1_1NBit" ],
        [ "ScaleOffset", "classhdf5_1_1filter_1_1ScaleOffset.html", "classhdf5_1_1filter_1_1ScaleOffset" ],
        [ "Shuffle", "classhdf5_1_1filter_1_1Shuffle.html", "classhdf5_1_1filter_1_1Shuffle" ],
        [ "SZip", "classhdf5_1_1filter_1_1SZip.html", "classhdf5_1_1filter_1_1SZip" ]
      ] ],
      [ "node", "namespacehdf5_1_1node.html", [
        [ "ChunkedDataset", "classhdf5_1_1node_1_1ChunkedDataset.html", "classhdf5_1_1node_1_1ChunkedDataset" ],
        [ "Dataset", "classhdf5_1_1node_1_1Dataset.html", "classhdf5_1_1node_1_1Dataset" ],
        [ "Group", "classhdf5_1_1node_1_1Group.html", "classhdf5_1_1node_1_1Group" ],
        [ "GroupView", "classhdf5_1_1node_1_1GroupView.html", "classhdf5_1_1node_1_1GroupView" ],
        [ "LinkTarget", "classhdf5_1_1node_1_1LinkTarget.html", "classhdf5_1_1node_1_1LinkTarget" ],
        [ "Link", "classhdf5_1_1node_1_1Link.html", "classhdf5_1_1node_1_1Link" ],
        [ "LinkIterator", "classhdf5_1_1node_1_1LinkIterator.html", "classhdf5_1_1node_1_1LinkIterator" ],
        [ "LinkView", "classhdf5_1_1node_1_1LinkView.html", "classhdf5_1_1node_1_1LinkView" ],
        [ "Node", "classhdf5_1_1node_1_1Node.html", "classhdf5_1_1node_1_1Node" ],
        [ "NodeIterator", "classhdf5_1_1node_1_1NodeIterator.html", "classhdf5_1_1node_1_1NodeIterator" ],
        [ "NodeView", "classhdf5_1_1node_1_1NodeView.html", "classhdf5_1_1node_1_1NodeView" ],
        [ "RecursiveLinkIterator", "classhdf5_1_1node_1_1RecursiveLinkIterator.html", "classhdf5_1_1node_1_1RecursiveLinkIterator" ],
        [ "RecursiveNodeIterator", "classhdf5_1_1node_1_1RecursiveNodeIterator.html", "classhdf5_1_1node_1_1RecursiveNodeIterator" ],
        [ "VirtualDataset", "classhdf5_1_1node_1_1VirtualDataset.html", "classhdf5_1_1node_1_1VirtualDataset" ]
      ] ],
      [ "property", "namespacehdf5_1_1property.html", [
        [ "AttributeCreationList", "classhdf5_1_1property_1_1AttributeCreationList.html", "classhdf5_1_1property_1_1AttributeCreationList" ],
        [ "CreationOrder", "classhdf5_1_1property_1_1CreationOrder.html", "classhdf5_1_1property_1_1CreationOrder" ],
        [ "ChunkCacheParameters", "classhdf5_1_1property_1_1ChunkCacheParameters.html", "classhdf5_1_1property_1_1ChunkCacheParameters" ],
        [ "DatasetAccessList", "classhdf5_1_1property_1_1DatasetAccessList.html", "classhdf5_1_1property_1_1DatasetAccessList" ],
        [ "DatasetCreationList", "classhdf5_1_1property_1_1DatasetCreationList.html", "classhdf5_1_1property_1_1DatasetCreationList" ],
        [ "DatasetTransferList", "classhdf5_1_1property_1_1DatasetTransferList.html", "classhdf5_1_1property_1_1DatasetTransferList" ],
        [ "DatatypeAccessList", "classhdf5_1_1property_1_1DatatypeAccessList.html", "classhdf5_1_1property_1_1DatatypeAccessList" ],
        [ "FileAccessList", "classhdf5_1_1property_1_1FileAccessList.html", "classhdf5_1_1property_1_1FileAccessList" ],
        [ "FileCreationList", "classhdf5_1_1property_1_1FileCreationList.html", "classhdf5_1_1property_1_1FileCreationList" ],
        [ "FileMountList", "classhdf5_1_1property_1_1FileMountList.html", "classhdf5_1_1property_1_1FileMountList" ],
        [ "GroupAccessList", "classhdf5_1_1property_1_1GroupAccessList.html", "classhdf5_1_1property_1_1GroupAccessList" ],
        [ "GroupCreationList", "classhdf5_1_1property_1_1GroupCreationList.html", "classhdf5_1_1property_1_1GroupCreationList" ],
        [ "LinkAccessList", "classhdf5_1_1property_1_1LinkAccessList.html", "classhdf5_1_1property_1_1LinkAccessList" ],
        [ "LinkCreationList", "classhdf5_1_1property_1_1LinkCreationList.html", "classhdf5_1_1property_1_1LinkCreationList" ],
        [ "CopyFlags", "classhdf5_1_1property_1_1CopyFlags.html", "classhdf5_1_1property_1_1CopyFlags" ],
        [ "ObjectCopyList", "classhdf5_1_1property_1_1ObjectCopyList.html", "classhdf5_1_1property_1_1ObjectCopyList" ],
        [ "ObjectCreationList", "classhdf5_1_1property_1_1ObjectCreationList.html", "classhdf5_1_1property_1_1ObjectCreationList" ],
        [ "Class", "classhdf5_1_1property_1_1Class.html", "classhdf5_1_1property_1_1Class" ],
        [ "List", "classhdf5_1_1property_1_1List.html", "classhdf5_1_1property_1_1List" ],
        [ "StringCreationList", "classhdf5_1_1property_1_1StringCreationList.html", "classhdf5_1_1property_1_1StringCreationList" ],
        [ "TypeCreationList", "classhdf5_1_1property_1_1TypeCreationList.html", "classhdf5_1_1property_1_1TypeCreationList" ],
        [ "VirtualDataMap", "classhdf5_1_1property_1_1VirtualDataMap.html", "classhdf5_1_1property_1_1VirtualDataMap" ],
        [ "VirtualDataMaps", "classhdf5_1_1property_1_1VirtualDataMaps.html", null ]
      ] ],
      [ "Context", "classhdf5_1_1Context.html", "classhdf5_1_1Context" ],
      [ "FixedLengthStringBuffer", "classhdf5_1_1FixedLengthStringBuffer.html", "classhdf5_1_1FixedLengthStringBuffer" ],
      [ "FixedLengthStringTrait", "structhdf5_1_1FixedLengthStringTrait.html", "structhdf5_1_1FixedLengthStringTrait" ],
      [ "FixedLengthStringTrait< std::string >", "structhdf5_1_1FixedLengthStringTrait_3_01std_1_1string_01_4.html", "structhdf5_1_1FixedLengthStringTrait_3_01std_1_1string_01_4" ],
      [ "FixedLengthStringTrait< std::vector< std::string > >", "structhdf5_1_1FixedLengthStringTrait_3_01std_1_1vector_3_01std_1_1string_01_4_01_4.html", "structhdf5_1_1FixedLengthStringTrait_3_01std_1_1vector_3_01std_1_1string_01_4_01_4" ],
      [ "IOWriteBuffer", "classhdf5_1_1IOWriteBuffer.html", "classhdf5_1_1IOWriteBuffer" ],
      [ "IOReadBuffer", "classhdf5_1_1IOReadBuffer.html", "classhdf5_1_1IOReadBuffer" ],
      [ "Iterator", "classhdf5_1_1Iterator.html", "classhdf5_1_1Iterator" ],
      [ "IteratorConfig", "classhdf5_1_1IteratorConfig.html", "classhdf5_1_1IteratorConfig" ],
      [ "ObjectHandle", "classhdf5_1_1ObjectHandle.html", "classhdf5_1_1ObjectHandle" ],
      [ "ObjectId", "classhdf5_1_1ObjectId.html", "classhdf5_1_1ObjectId" ],
      [ "Path", "classhdf5_1_1Path.html", "classhdf5_1_1Path" ],
      [ "VarLengthBufferTrait", "structhdf5_1_1VarLengthBufferTrait.html", "structhdf5_1_1VarLengthBufferTrait" ],
      [ "VarLengthStringTrait", "structhdf5_1_1VarLengthStringTrait.html", "structhdf5_1_1VarLengthStringTrait" ],
      [ "VarLengthStringTrait< std::string >", "structhdf5_1_1VarLengthStringTrait_3_01std_1_1string_01_4.html", "structhdf5_1_1VarLengthStringTrait_3_01std_1_1string_01_4" ],
      [ "VarLengthStringTrait< std::vector< std::string > >", "structhdf5_1_1VarLengthStringTrait_3_01std_1_1vector_3_01std_1_1string_01_4_01_4.html", "structhdf5_1_1VarLengthStringTrait_3_01std_1_1vector_3_01std_1_1string_01_4_01_4" ],
      [ "Version", "classhdf5_1_1Version.html", "classhdf5_1_1Version" ],
      [ "ArrayAdapter", "classhdf5_1_1ArrayAdapter.html", "classhdf5_1_1ArrayAdapter" ]
    ] ]
];