if(H5CPP_WITH_MPI)
  set(HDF5_PREFER_PARALLEL TRUE)
endif()

find_package(HDF5)
message(STATUS "==============================================================")
message(STATUS "========================Found HDF5============================")
message(STATUS "==============================================================")
message(STATUS "Found HDF5 libraries in: ${HDF5_LIBRARY_DIRS}")
message(STATUS "Found HDF5 libraries: ${HDF5_LIBRARIES}")
message(STATUS "Found HDF5 HL libraries: ${HDF5_HL_LIBRARIES}")
message(STATUS "Found HDF5 headers: ${HDF5_INCLUDE_DIRS}")
message(STATUS "Found HDF5 definitions: ${HDF5_DEFINITIONS}")
message(STATUS "Found HDF5 HDF5_VERSION = ${HDF5_VERSION}")
message(STATUS "Found HDF5 HDF5_IS_PARALLEL = ${HDF5_IS_PARALLEL}")
message(STATUS "==============================================================")


if(H5CPP_WITH_MPI)
  if(NOT HDF5_IS_PARALLEL)
    message(FATAL_ERROR "The HDF5 version found does not support MPI")
  endif()
endif()
